//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppRest.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="fys.integrationFord.service", ConfigurationName="ServiceReference1.FileReceptorServicePort")]
    public interface FileReceptorServicePort {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ingresarFactura no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ConsoleAppRest.ServiceReference1.ingresarFacturaResponse1 ingresarFactura(ConsoleAppRest.ServiceReference1.ingresarFacturaRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleAppRest.ServiceReference1.ingresarFacturaResponse1> ingresarFacturaAsync(ConsoleAppRest.ServiceReference1.ingresarFacturaRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="fys.integrationFord.service")]
    public partial class ingresarFacturaRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ingresarFacturaType ingresarFacturaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ingresarFacturaType ingresarFactura {
            get {
                return this.ingresarFacturaField;
            }
            set {
                this.ingresarFacturaField = value;
                this.RaisePropertyChanged("ingresarFactura");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fys.integrationFord.service")]
    public partial class ingresarFacturaType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dealerIDField;
        
        private string leadIDField;
        
        private string formaPagoField;
        
        private string tipoFacturaField;
        
        private string nombreField;
        
        private string apellidoField;
        
        private string documentoField;
        
        private string modeloField;
        
        private string versionField;
        
        private string colorField;
        
        private string vinField;
        
        private System.DateTime fechaFacturaField;
        
        private string monedaField;
        
        private string valorFacturaSinImpuestosField;
        
        private string valorFacturaConImpuestosField;
        
        private string numeroFacturaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string dealerID {
            get {
                return this.dealerIDField;
            }
            set {
                this.dealerIDField = value;
                this.RaisePropertyChanged("dealerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string leadID {
            get {
                return this.leadIDField;
            }
            set {
                this.leadIDField = value;
                this.RaisePropertyChanged("leadID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string formaPago {
            get {
                return this.formaPagoField;
            }
            set {
                this.formaPagoField = value;
                this.RaisePropertyChanged("formaPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string tipoFactura {
            get {
                return this.tipoFacturaField;
            }
            set {
                this.tipoFacturaField = value;
                this.RaisePropertyChanged("tipoFactura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
                this.RaisePropertyChanged("documento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
                this.RaisePropertyChanged("modelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
                this.RaisePropertyChanged("color");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string vin {
            get {
                return this.vinField;
            }
            set {
                this.vinField = value;
                this.RaisePropertyChanged("vin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=11)]
        public System.DateTime fechaFactura {
            get {
                return this.fechaFacturaField;
            }
            set {
                this.fechaFacturaField = value;
                this.RaisePropertyChanged("fechaFactura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
                this.RaisePropertyChanged("moneda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string valorFacturaSinImpuestos {
            get {
                return this.valorFacturaSinImpuestosField;
            }
            set {
                this.valorFacturaSinImpuestosField = value;
                this.RaisePropertyChanged("valorFacturaSinImpuestos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string valorFacturaConImpuestos {
            get {
                return this.valorFacturaConImpuestosField;
            }
            set {
                this.valorFacturaConImpuestosField = value;
                this.RaisePropertyChanged("valorFacturaConImpuestos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string numeroFactura {
            get {
                return this.numeroFacturaField;
            }
            set {
                this.numeroFacturaField = value;
                this.RaisePropertyChanged("numeroFactura");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="fys.integrationFord.service")]
    public partial class statusType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="fys.integrationFord.service")]
    public partial class ingresarFacturaResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private statusType statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public statusType status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ingresarFacturaRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="fys.integrationFord.service", Order=0)]
        public ConsoleAppRest.ServiceReference1.ingresarFacturaRequest ingresarFacturaRequest;
        
        public ingresarFacturaRequest1() {
        }
        
        public ingresarFacturaRequest1(ConsoleAppRest.ServiceReference1.ingresarFacturaRequest ingresarFacturaRequest) {
            this.ingresarFacturaRequest = ingresarFacturaRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ingresarFacturaResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="fys.integrationFord.service", Order=0)]
        public ConsoleAppRest.ServiceReference1.ingresarFacturaResponse ingresarFacturaResponse;
        
        public ingresarFacturaResponse1() {
        }
        
        public ingresarFacturaResponse1(ConsoleAppRest.ServiceReference1.ingresarFacturaResponse ingresarFacturaResponse) {
            this.ingresarFacturaResponse = ingresarFacturaResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FileReceptorServicePortChannel : ConsoleAppRest.ServiceReference1.FileReceptorServicePort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileReceptorServicePortClient : System.ServiceModel.ClientBase<ConsoleAppRest.ServiceReference1.FileReceptorServicePort>, ConsoleAppRest.ServiceReference1.FileReceptorServicePort {
        
        public FileReceptorServicePortClient() {
        }
        
        public FileReceptorServicePortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileReceptorServicePortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileReceptorServicePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileReceptorServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleAppRest.ServiceReference1.ingresarFacturaResponse1 ConsoleAppRest.ServiceReference1.FileReceptorServicePort.ingresarFactura(ConsoleAppRest.ServiceReference1.ingresarFacturaRequest1 request) {
            return base.Channel.ingresarFactura(request);
        }
        
        public ConsoleAppRest.ServiceReference1.ingresarFacturaResponse ingresarFactura(ConsoleAppRest.ServiceReference1.ingresarFacturaRequest ingresarFacturaRequest) {
            ConsoleAppRest.ServiceReference1.ingresarFacturaRequest1 inValue = new ConsoleAppRest.ServiceReference1.ingresarFacturaRequest1();
            inValue.ingresarFacturaRequest = ingresarFacturaRequest;
            ConsoleAppRest.ServiceReference1.ingresarFacturaResponse1 retVal = ((ConsoleAppRest.ServiceReference1.FileReceptorServicePort)(this)).ingresarFactura(inValue);
            return retVal.ingresarFacturaResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleAppRest.ServiceReference1.ingresarFacturaResponse1> ConsoleAppRest.ServiceReference1.FileReceptorServicePort.ingresarFacturaAsync(ConsoleAppRest.ServiceReference1.ingresarFacturaRequest1 request) {
            return base.Channel.ingresarFacturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppRest.ServiceReference1.ingresarFacturaResponse1> ingresarFacturaAsync(ConsoleAppRest.ServiceReference1.ingresarFacturaRequest ingresarFacturaRequest) {
            ConsoleAppRest.ServiceReference1.ingresarFacturaRequest1 inValue = new ConsoleAppRest.ServiceReference1.ingresarFacturaRequest1();
            inValue.ingresarFacturaRequest = ingresarFacturaRequest;
            return ((ConsoleAppRest.ServiceReference1.FileReceptorServicePort)(this)).ingresarFacturaAsync(inValue);
        }
    }
}
